# Generated by Django 3.1.2 on 2021-04-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published_date',
            field=models.DateField(auto_now=True),
        ),
    ]
