# Generated by Django 3.1.2 on 2021-04-06 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funded',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0, 'The funded value was not greater than 0'), django.core.validators.MaxValueValidator(100, 'The funded value was not less than 100')], verbose_name='Funded'),
        ),
    ]
