# Generated by Django 3.1.2 on 2021-04-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210406_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_name',
            field=models.CharField(max_length=40, null=True, verbose_name='File name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='days_left',
            field=models.IntegerField(blank=True, null=True, verbose_name='Days left'),
        ),
    ]
