# Generated by Django 3.1.2 on 2021-04-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210406_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_name',
        ),
        migrations.AddField(
            model_name='project',
            name='image_file',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image file name'),
        ),
    ]
