# Generated by Django 3.1.2 on 2021-04-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210406_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, verbose_name='Name')),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-published_date'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='image_file',
            field=models.ImageField(null=True, upload_to='main/', verbose_name='Image file name'),
        ),
    ]
