# Generated by Django 3.1.2 on 2021-05-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210504_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_date',
            field=models.DateField(auto_now=True, verbose_name='Registered date'),
        ),
    ]
