# Generated by Django 3.1.2 on 2021-05-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_registered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='csrf_token',
        ),
    ]
